[package]
name = "sarus-suite-podman-driver"
version = "0.1.1"
edition = "2024"

[dependencies]
raster = { git = "https://github.com/sarus-suite/raster", branch = "small_edf" }
bstr = "1.12.0"
anyhow = "1.0.100"
